# Generated by Django 5.2.8 on 2025-11-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
