# Generated by Django 5.2.8 on 2025-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', max_length=3),
        ),
    ]
